package net.gini.android.bank.sdk.exampleapp.ui.resources

import java.time.LocalDate

/**
 * Fixture data for the Skonto screen and Return-Assistant-plus-Skonto tests.
 *
 * ## Why two of these are generated with a 2028 invoice date
 *
 * A skonto window is relative to the invoice date and only 7-14 days wide, so a real
 * invoice's discount stops being claimable about two weeks after it was issued.
 * `GetSkontoEdgeCaseUseCase` maps any `skontoDueDate` before today to
 * `SkontoEdgeCase.SkontoExpired`, and `GetSkontoDefaultSelectionStateUseCase` then arrives
 * with the discount switched off. A committed fixture can therefore only hold the
 * *claimable* state by printing an invoice date in the future — the same approach
 * [DueDateFixtures] takes for `paymentDueDate`.
 *
 * The expired states need no such trick, and use real invoices.
 *
 * | Asset | Invoice date | Skonto deadline | State under test |
 * |---|---|---|---|
 * | [VALID_ASSET] | 05.08.2028 | 19.08.2028 | claimable, no line items |
 * | [RA_VALID_ASSET] | 05.08.2028 | 19.08.2028 | skonto only — its position table does not extract |
 * | [RA_SKONTO_ASSET] | 05.08.2024 | 19.08.2024 | line items + skonto terms, discount expired |
 * | [PAST_ASSET] | 01.08.2025 | 08.08.2025 | expired, no line items |
 * | [RA_PAST_ASSET] | 15.08.2024 | 29.08.2024 | expired, two line items |
 *
 * [VALID_ASSET] and [RA_VALID_ASSET] are generated by
 * `src/androidTest/scripts/fixtures/gen_invoice_skonto_valid.py` and
 * `gen_invoice_skonto_ra_valid.py`. [PAST_ASSET] and [RA_PAST_ASSET] are real invoices
 * (a FreeFinance and an OTTO one) and are not regenerable — their printed dates are
 * already in the past, which is exactly what those cases need.
 *
 * REFRESH DEADLINE: regenerate [VALID_ASSET] and [RA_VALID_ASSET] with a later invoice
 * date (and update [VALID_SKONTO_DUE_DATE]) before mid-2028, when 19.08.2028 stops being
 * comfortably in the future. Re-validate the regenerated fixtures against the Gini API
 * before committing them — a different font produces different image bytes, and the
 * extraction is not guaranteed to survive that.
 */
object SkontoFixtures {

    /** A claimable discount and no line items: the standalone Skonto screen. */
    const val VALID_ASSET = "skonto_valid.jpeg"

    /**
     * Generated with a claimable discount and a printed position table — but the table is
     * **not** extracted as `lineItems`, so it lands on the standalone Skonto screen and is
     * unusable for the digital invoice case (build `13a5f54e`). Retained only so the
     * generator's output has a name; [RA_SKONTO_ASSET] is what the tests use.
     */
    const val RA_VALID_ASSET = "skonto_ra_valid.jpeg"

    /** An expired discount and no line items: the standalone Skonto screen's edge case. */
    const val PAST_ASSET = "skonto_past.pdf"

    /**
     * Line items **and** skonto terms in one document: the digital invoice screen's skonto
     * row. Its discount expired in 2024, so the row arrives with the toggle off.
     *
     * ## What was measured before settling on this one
     *
     * The digital invoice screen only shows a skonto row when a single analysis result
     * carries `lineItems` *and* `skontoDiscounts`. Build `13a5f54e` measured the
     * alternatives, and each gave exactly one of the two:
     *
     * | Candidate | `lineItems` | `skontoDiscounts` |
     * |---|---|---|
     * | `skonto_ra_valid.jpeg` (generated, prints a position table) | no | yes |
     * | `Testrechnung-RA-Skonto.pdf` (OTTO invoice) | yes | no |
     *
     * So a printed position table is not necessarily extracted, and neither are printed
     * skonto terms — which is why a fixture has to be measured against the API rather than
     * chosen by reading it. This one prints "Bei Zahlung innerhalb von 14 Tagen werden 5 %
     * Skonto gewährt" and a position table with a gift-card addon; **whether the backend
     * returns both is still unverified.**
     */
    const val RA_SKONTO_ASSET = "Testrechnung-RA-Giftcard-Skonto.pdf"

    /**
     * Line items only — its skonto terms did not extract (build `13a5f54e`, which reached
     * the digital invoice screen showing "1x Bettwäsche 2tg" with no skonto row). Kept as a
     * documented fallback rather than deleted, so the measurement is not lost.
     */
    const val RA_PAST_ASSET = "Testrechnung-RA-Skonto.pdf"

    /** Must match the skonto deadline printed on [VALID_ASSET] and [RA_VALID_ASSET]. */
    val VALID_SKONTO_DUE_DATE: LocalDate = LocalDate.of(2028, 8, 19)

    /**
     * The full amount printed on [VALID_ASSET] and [RA_VALID_ASSET], as the extraction
     * reports it. Assertions stay on direction of change rather than exact figures wherever
     * the backend's own rounding could differ, but validation bounds need a number.
     */
    const val VALID_FULL_AMOUNT = "500.00"
}
