package net.gini.android.bank.sdk.exampleapp.ui.resources

import java.time.LocalDate

/**
 * Fixture data for the Skonto screen and Return-Assistant-plus-Skonto tests.
 *
 * ## Why two of these are generated with a 2028 invoice date
 *
 * A skonto window is relative to the invoice date and only 7-14 days wide, so a real
 * invoice's discount stops being claimable about two weeks after it was issued.
 * `GetSkontoEdgeCaseUseCase` maps any `skontoDueDate` before today to
 * `SkontoEdgeCase.SkontoExpired`, and `GetSkontoDefaultSelectionStateUseCase` then arrives
 * with the discount switched off. A committed fixture can therefore only hold the
 * *claimable* state by printing an invoice date in the future — the same approach
 * [DueDateFixtures] takes for `paymentDueDate`.
 *
 * The expired states need no such trick, and use real invoices.
 *
 * | Asset | Invoice date | Skonto deadline | State under test |
 * |---|---|---|---|
 * | [VALID_ASSET] | 05.08.2028 | 19.08.2028 | claimable, no line items |
 * | [RA_VALID_ASSET] | 05.08.2028 | 19.08.2028 | skonto only — its position table does not extract |
 * | [PAST_ASSET] | 01.08.2025 | 08.08.2025 | expired, no line items |
 * | [RA_PAST_ASSET] | 15.08.2024 | 29.08.2024 | expired, two line items |
 *
 * [VALID_ASSET] and [RA_VALID_ASSET] are generated by
 * `src/androidTest/scripts/fixtures/gen_invoice_skonto_valid.py` and
 * `gen_invoice_skonto_ra_valid.py`. [PAST_ASSET] and [RA_PAST_ASSET] are real invoices
 * (a FreeFinance and an OTTO one) and are not regenerable — their printed dates are
 * already in the past, which is exactly what those cases need.
 *
 * REFRESH DEADLINE: regenerate [VALID_ASSET] and [RA_VALID_ASSET] with a later invoice
 * date (and update [VALID_SKONTO_DUE_DATE]) before mid-2028, when 19.08.2028 stops being
 * comfortably in the future. Re-validate the regenerated fixtures against the Gini API
 * before committing them — a different font produces different image bytes, and the
 * extraction is not guaranteed to survive that.
 *
 * ## No fixture yields line items *and* a skonto discount
 *
 * The digital invoice screen only shows a skonto row when a single analysis result carries
 * `lineItems` **and** `skontoDiscounts`. Build `13a5f54e` measured both candidates on a real
 * device and each returned exactly one of the two:
 *
 * | Candidate | `lineItems` | `skontoDiscounts` |
 * |---|---|---|
 * | [RA_VALID_ASSET] (generated, prints a position table) | no | yes |
 * | [RA_PAST_ASSET] (OTTO invoice, prints skonto terms) | yes | no |
 *
 * So a printed position table is not necessarily extracted, and neither are printed skonto
 * terms — which is why a fixture has to be measured against the API rather than chosen by
 * reading it. That gap is what keeps [net.gini.android.bank.sdk.exampleapp.ui.testcases.DigitalInvoiceSkontoTests]
 * out of every BrowserStack script.
 */
object SkontoFixtures {

    /** A claimable discount and no line items: the standalone Skonto screen. */
    const val VALID_ASSET = "skonto_valid.jpeg"

    /**
     * Generated with a claimable discount and a printed position table — but the table is
     * **not** extracted as `lineItems`, so it lands on the standalone Skonto screen and is
     * unusable for the digital invoice case (build `13a5f54e`).
     */
    const val RA_VALID_ASSET = "skonto_ra_valid.jpeg"

    /** An expired discount and no line items: the standalone Skonto screen's edge case. */
    const val PAST_ASSET = "skonto_past.pdf"

    /**
     * The repository's Return-Assistant-plus-skonto invoice: an OTTO invoice printing a
     * position table *and* skonto terms.
     *
     * Only the line items extract — build `13a5f54e` reached the digital invoice screen
     * showing "1x Bettwäsche 2tg" with no skonto row, so `skontoDiscounts` came back empty.
     * It is still the closest fixture the repository has to TC-013, which is why
     * [net.gini.android.bank.sdk.exampleapp.ui.testcases.DigitalInvoiceSkontoTests] uses it,
     * and why that class is excluded from every run rather than deleted.
     */
    const val RA_PAST_ASSET = "Testrechnung-RA-Skonto.pdf"

    /** Must match the skonto deadline printed on [VALID_ASSET] and [RA_VALID_ASSET]. */
    val VALID_SKONTO_DUE_DATE: LocalDate = LocalDate.of(2028, 8, 19)

    /**
     * The full amount printed on [VALID_ASSET] and [RA_VALID_ASSET], as the extraction
     * reports it. Assertions stay on direction of change rather than exact figures wherever
     * the backend's own rounding could differ, but validation bounds need a number.
     */
    const val VALID_FULL_AMOUNT = "500.00"
}
