# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane         

load 'util/tags.rb'
load 'util/lanes.rb'

default_platform(:android)

platform :android do

  desc <<~DOC
    Publish a project to Maven Central.
    
    Parameters:
      project_id    - the id of the project to be released (e.g., health-sdk, health-api-lib)"
      module_id     - the id of the project's module to be released (e.g., sdk, lib)"
      git_tag       - the git tag name used to release the project
      build_number  - the build number to use in the release"
  DOC
  lane :publish_to_maven do |options|
    (project_id, module_id, git_tag, build_number) = 
      check_and_get_options(options, [:project_id, :module_id, :git_tag, :build_number], UI)

    version = get_example_app_version(project_id, "example-app", git_tag, UI)

    UI.message "Will release to Maven Central module :#{project_id}:#{module_id} with version #{version} and build number #{build_number}"
    
    # TODO: release to maven central
    gradle(
      task: "#{project_id}:#{module_id}:publishReleasePublicationToMavenLocal",
      properties: { "versionName" => version, "versionCode" => build_number }
    )

    UI.success "Released to Maven Central module :#{project_id}:#{module_id} with version #{version} and build number #{build_number}"
  end

end

