name: Release docs for Bank SDK

on:
  push:
    tags:
      - 'bank-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
      - 'bank-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9];doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy2.7'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: release documentation
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'release_documentation'
          options: >
            { 
              "project_id": "bank-sdk",
              "module_id": "sdk",
              "documentation_title": "Gini Bank SDK for Android",
              "links_to_projects": "[{\\\"project_id\\\": \\\"capture-sdk\\\", \\\"module_id\\\": \\\"sdk\\\"}]",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: bank-sdk-documentation
          path: bank-sdk/sdk/build/docs
