name: Release Bank SDK

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/bank-sdk.check.yml
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}
      BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD: ${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}
        
  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: build release example app for QA
        run: >
        ./gradlew bank-sdk:example-app:assembleQaExampleAppRelease
        -PclientId="gini-mobile-test" 
        -PclientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"
        -PreleaseKeystoreFile="screen_api_example.jks"
        -PreleaseKeystorePassword='${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'
        -PreleaseKeyAlias="screen_api_example"
        -PreleaseKeyPassword='${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'

      - name: archive release example app for QA
        uses: actions/upload-artifact@v3
        with:
          name: bank-sdk-example-app-qa-release
          path: bank-sdk/example-app/build/outputs/apk/qaExampleApp/release

      - name: build release example app for production
        run: >
        ./gradlew bank-sdk:example-app:assembleProdExampleAppRelease
        -PclientId="gini-mobile-test" 
        -PclientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"
        -PreleaseKeystoreFile="screen_api_example.jks"
        -PreleaseKeystorePassword='${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'
        -PreleaseKeyAlias="screen_api_example"
        -PreleaseKeyPassword='${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'
        
      - name: archive release example app for production
        uses: actions/upload-artifact@v3
        with:
          name: bank-sdk-example-app-prod-release
          path: bank-sdk/example-app/build/outputs/apk/prodExampleApp/release
    

      - name: Install appcenter-cli
        run: |
          npm install -g appcenter-cli
        
      - name: Distribute ipa to App Center
        uses: akiojin/appcenter-distribute-github-action@v1.4.11
        with:
          token: ${{ secrets.TODO }}
          path: GiniMerchantSDKExample.ipa
          app: Gini-Team-Organization/Screen-API-Example-Gini-Pay-Bank-SDK
          group: 'Public'
          release_notes: ${{ format('{{ {0} {1} }}', github.ref, github.sha) }}             
