name: Release docs for Bank API Library

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - 'bank-api-library;[0-9]+.[0-9]+.[0-9]+;doc**'
      - 'bank-api-library;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9];doc**'
  workflow_call:
    secrets:
      MOBILE_CI_APP_ID:
        required: true
      MOBILE_CI_APP_PRIVATE_KEY:
        required: true

jobs:
  publish:
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.publish.docs.yml
    with:
      project_id: 'bank-api-library'
      module_id: 'library'
      documentation_title: 'Gini Bank API Library for Android'
      git_tag: ${{ github.ref }}
      artifact_name: 'bank-api-library-documentation'
      artifact_path: 'bank-api-library/library/build/docs'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
