name: Release docs for Bank SDK

on:
  push:
    tags:
      - 'bank-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.x'

      - name: release documentation
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'release_documentation'
          options: >
            { 
              "project_id": "bank-sdk",
              "module_id": "sdk",
              "documentation_title": "Gini Bank SDK for Android",
              "links_to_projects": '[{"project_id": "capture-sdk", "module_id": "sdk"}]'
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: bank-sdk-documentation
          path: bank-sdk/sdk/build/docs
