name: Build Bank SDK alternative version

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET:
        required: true
      BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD:
        required: true

jobs:
  build-example-apps:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: build unique release example app for QA
        run: >
          ./gradlew bank-sdk:example-app:assembleQaUniqueExampleAppRelease
          -PclientId="gini-mobile-test" 
          -PclientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"
          -PreleaseKeystoreFile="screen_api_example.jks"
          -PreleaseKeystorePassword='${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'
          -PreleaseKeyAlias="screen_api_example"
          -PreleaseKeyPassword='${{ secrets.BANK_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'

      - name: archive unique release example app for QA
        uses: actions/upload-artifact@v4
        with:
          name: bank-sdk-example-app-qa-release
          path: bank-sdk/example-app/build/outputs/apk/qaUniqueExampleApp/release