name: Release Bank API Library

on:
  push:
    tags:
      - 'bank-api-library;[0-9]+.[0-9]+.[0-9]+'
      - 'bank-api-library;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9]'

jobs:
  check:
    uses: ./.github/workflows/bank-api-library.check.yml
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true
    
      - name: "publish to Maven Central staging repo at https://oss.sonatype.org/service/local/staging/deploy/maven2/"
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'publish_to_maven_repo'
          options: >
            {
              "repo_url": "https://oss.sonatype.org/service/local/staging/deploy/maven2/",
              "repo_user": "${{ secrets.MAVEN_CENTRAL_USER_TOKEN_USERNAME }}",
              "repo_password": "${{ secrets.MAVEN_CENTRAL_USER_TOKEN_PASSWORD }}",
              "project_id": "bank-api-library",
              "module_id": "library",
              "build_number": "${{ github.run_number }}",
              "git_tag": "${{ github.ref }}",
              "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
              "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
            }

  release-documentation:
    needs: release
    uses: ./.github/workflows/bank-api-library.docs.release.yml
    secrets:
      RELEASE_GITHUB_USER: ${{ secrets.RELEASE_GITHUB_USER }}
      RELEASE_GITHUB_PASSWORD: ${{ secrets.RELEASE_GITHUB_PASSWORD }}
