name: Build docs for Capture SDK

permissions:
  content: read

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'capture-sdk/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy2.7'

      - name: setup ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: build sdk documentation
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7  # v3.1.0
        with:
          lane: 'build_documentation'
          options: >
            { 
              "project_id": "capture-sdk",
              "module_id": "sdk"
            }

      - name: archive sdk documentation
        uses: actions/upload-artifact@v4
        with:
          name: capture-sdk-documentation
          path: capture-sdk/sdk/build/docs

      - name: build default network library documentation
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7  # v3.1.0
        with:
          lane: 'build_documentation'
          options: >
            {
              "project_id": "capture-sdk",
              "module_id": "default-network"
            }

      - name: archive default network library documentation
        uses: actions/upload-artifact@v4
        with:
          name: capture-sdk-default-network-documentation
          path: capture-sdk/default-network/build/docs
