name: Build docs for Capture SDK

on:
  push:
    paths:
      - 'capture-sdk/**'
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    types: [opened, edited, reopened]
    paths:
      - 'capture-sdk/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy2.7'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: build sdk documentation
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'build_documentation'
          options: >
            { 
              "project_id": "capture-sdk",
              "module_id": "sdk"
            }

      - name: archive sdk documentation
        uses: actions/upload-artifact@v4
        with:
          name: capture-sdk-documentation
          path: capture-sdk/sdk/build/docs

      - name: build default network library documentation
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'build_documentation'
          options: >
            {
              "project_id": "capture-sdk",
              "module_id": "default-network"
            }

      - name: archive default network library documentation
        uses: actions/upload-artifact@v4
        with:
          name: capture-sdk-default-network-documentation
          path: capture-sdk/default-network/build/docs
