name: Release docs for Capture SDK

on:
  push:
    tags:
      - 'capture-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.x'

      - name: release sdk documentation
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'release_documentation'
          options: >
            { 
              "project_id": "capture-sdk",
              "module_id": "sdk",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive sdk documentation
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-documentation
          path: capture-sdk/sdk/build/docs

      - name: release default network library documentation
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'release_documentation'
          options: >
            {
              "project_id": "capture-sdk",
              "module_id": "default-network",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive default network library documentation
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-default-network-documentation
          path: capture-sdk/default-network/build/docs