name: Check Capture SDK

on:
  push:
    paths:
      - 'capture-sdk/**'
      - 'bank-api-library/**'
      - 'core-api-library/**'
      - 'gradle/**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'capture-sdk/**'
      - 'bank-api-library/**'
      - 'core-api-library/**'
      - 'gradle/**'
  workflow_call:
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run unit tests
        run: ./gradlew capture-sdk:sdk:testDebugUnitTest

      - name: archive unit test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-unit-test-results
          path: capture-sdk/sdk/build/reports/tests

      - name: create unit test coverage report
        run: ./gradlew capture-sdk:sdk:jacocoTestDebugUnitTestReport

      - name: archive unit test coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-unit-test-coverage
          path: capture-sdk/sdk/build/jacoco/jacocoHtml

  build-example-apps:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: build screen api example app
        run: >
          ./gradlew capture-sdk:screen-api-example-app:assembleDebug 
          -PclientId="gini-mobile-test" 
          -PclientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"

      - name: archive screen api example app
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-screen-api-example-app
          path: capture-sdk/screen-api-example-app/build/outputs/apk

      - name: build component api example app
        run: >
          ./gradlew capture-sdk:component-api-example-app:assembleDebug
          -PclientId="gini-mobile-test"
          -PclientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"

      - name: archive component api example app
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-component-api-example-app
          path: capture-sdk/component-api-example-app/build/outputs/apk

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run checkstyle
        run: ./gradlew capture-sdk:sdk:checkstyle

      - name: archive checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-checkstyle-report
          path: capture-sdk/sdk/build/reports/checkstyle/*.html

  pmd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run pmd
        run: ./gradlew capture-sdk:sdk:pmd

      - name: archive pmd report
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-pmd-report
          path: capture-sdk/sdk/build/reports/pmd/*.html

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run android lint
        run: ./gradlew capture-sdk:sdk:lint

      - name: archive android lint report
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-android-lint-report
          path: capture-sdk/sdk/build/reports/lint-results*.html

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run detekt
        run: ./gradlew capture-sdk:sdk:detekt

      - name: archive detekt report
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-detekt-report
          path: capture-sdk/sdk/build/reports/detekt/*.html

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run ktlint
        run: ./gradlew capture-sdk:sdk:ktlintCheck

      - name: archive ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: capture-sdk-ktlint-report
          path: capture-sdk/sdk/build/reports/ktlint/**/*.html
