name: Release docs for Capture SDK

permissions:
  contents: read

on:
  push:
    tags:
      - 'capture-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
      - 'capture-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9];doc**'
  workflow_call:
    secrets:
      MOBILE_CI_APP_ID:
        required: true
      MOBILE_CI_APP_PRIVATE_KEY:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}

jobs:
  publish-sdk:
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.publish.docs.yml
    with:
      project_id: 'capture-sdk'
      module_id: 'sdk'
      documentation_title: 'Gini Capture SDK for Android'
      git_tag: ${{ github.ref }}
      artifact_name: 'capture-sdk-documentation'
      artifact_path: 'capture-sdk/sdk/build/docs'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}

  publish-default-network:
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.publish.docs.yml
    with:
      project_id: 'capture-sdk'
      module_id: 'default-network'
      documentation_title: 'Gini Capture SDK for Android'
      git_tag: ${{ github.ref }}
      artifact_name: 'capture-sdk-default-network-documentation'
      artifact_path: 'capture-sdk/default-network/build/docs'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
