name: Release docs for Capture SDK

on:
  workflow_dispatch:
  push:
    tags:
      - 'capture-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
      - 'capture-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9];doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy2.7'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: release sdk documentation
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'release_documentation'
          options: >
            { 
              "project_id": "capture-sdk",
              "module_id": "sdk",
              "documentation_title": "Gini Capture SDK for Android",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive sdk documentation
        uses: actions/upload-artifact@v4
        with:
          name: capture-sdk-documentation
          path: capture-sdk/sdk/build/docs

      - name: release default network library documentation
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'release_documentation'
          options: >
            {
              "project_id": "capture-sdk",
              "module_id": "default-network",
              "documentation_title": "Gini Capture SDK for Android",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive default network library documentation
        uses: actions/upload-artifact@v4
        with:
          name: capture-sdk-default-network-documentation
          path: capture-sdk/default-network/build/docs