name: Check Core API Library

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'core-api-library/**'
      - 'gradle/**'
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 22, 26, 31 ]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: enable KVM group perms for emulator
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: avd cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-x86_64-${{ matrix.api-level }}-${{ github.ref_name }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: run instrumented tests
        timeout-minutes: 20
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: >
            adb uninstall net.gini.android.core.api.test ;
            ./gradlew core-api-library:library:connectedCheck && killall -INT crashpad_handler || true

      - name: archive instrumented test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: core-api-library-instrumented-test-results-api-level-${{ matrix.api-level }}
          path: core-api-library/library/build/outputs/androidTest-results/connected

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: run checkstyle
        run: ./gradlew core-api-library:library:checkstyle

      - name: archive checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: core-api-library-checkstyle-report
          path: core-api-library/library/build/reports/checkstyle/*.html

  pmd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: run pmd
        run: ./gradlew core-api-library:library:pmd

      - name: archive pmd report
        uses: actions/upload-artifact@v4
        with:
          name: core-api-library-pmd-report
          path: core-api-library/library/build/reports/pmd/*.html

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: run android lint
        run: ./gradlew core-api-library:library:lint

      - name: archive android lint report
        uses: actions/upload-artifact@v4
        with:
          name: core-api-library-android-lint-report
          path: core-api-library/library/build/reports/lint-results*.html

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: run detekt
        run: ./gradlew core-api-library:library:detekt

      - name: archive detekt report
        uses: actions/upload-artifact@v4
        with:
          name: core-api-library-detekt-report
          path: core-api-library/library/build/reports/detekt/*.html

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: run ktlint
        run: ./gradlew core-api-library:library:ktlintCheck

      - name: archive ktlint report
        uses: actions/upload-artifact@v4
        with:
          name: core-api-library-ktlint-report
          path: core-api-library/library/build/reports/ktlint/**/*.html
          