name: Check Core API Library

on:
  push:
    paths:
      - 'core-api-library/**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'core-api-library/**'
  workflow_call:
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET:
        required: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: avd cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-x86_64-${{ matrix.api-level }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: run instrumented tests
        timeout-minutes: 20
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: >
            ./gradlew
            core-api-library:library:connectedCheck
            -PtestClientId="gini-mobile-test"
            -PtestClientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"
            -PtestApiType="DEFAULT"
            -PtestApiUri="https://pay-api.gini.net"
            -PtestUserCenterUri="https://user.gini.net"

      - name: archive instrumented test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: core-api-library-instrumented-test-results
          path: core-api-library/library/build/outputs/androidTest-results/connected

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run checkstyle
        run: ./gradlew core-api-library:library:checkstyle

      - name: archive checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: core-api-library-checkstyle-report
          path: core-api-library/library/build/reports/checkstyle/*.html

  pmd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run pmd
        run: ./gradlew core-api-library:library:pmd

      - name: archive pmd report
        uses: actions/upload-artifact@v2
        with:
          name: core-api-library-pmd-report
          path: core-api-library/library/build/reports/pmd/*.html

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run android lint
        run: ./gradlew core-api-library:library:lint

      - name: archive android lint report
        uses: actions/upload-artifact@v2
        with:
          name: core-api-library-android-lint-report
          path: core-api-library/library/build/reports/lint-results*.html

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run detekt
        run: ./gradlew core-api-library:library:detekt

      - name: archive detekt report
        uses: actions/upload-artifact@v2
        with:
          name: core-api-library-detekt-report
          path: core-api-library/library/build/reports/detekt/*.html

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run ktlint
        run: ./gradlew core-api-library:library:ktlintCheck

      - name: archive ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: core-api-library-ktlint-report
          path: core-api-library/library/build/reports/ktlint/**/*.html
          