name: Build docs for Health API Library

on:
  push:
    paths:
      - 'health-api-library/**'
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'health-api-library/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7.x'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: build documentation
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'build_documentation'
          options: >
            { 
              "project_id": "health-api-library", 
              "module_id": "library"
            }

      - name: archive documentation
        uses: actions/upload-artifact@v3
        with:
          name: health-api-library-documentation
          path: health-api-library/library/build/docs