name: Check Health API Library
on: [push]
#  push:
#    paths:
#      - 'health-api-library/**'
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [22, 26, 31]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: avd cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-x86_64-${{ matrix.api-level }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: run instrumented tests
        env:
          client_id: ${{ secrets.HEALTH_API_LIBRARY_TEST_CLIENT_ID }}
          client_secret: ${{ secrets.HEALTH_API_LIBRARY_TEST_CLIENT_SECRET }}
          api_uri: "https://pay-api.gini.net"
          user_center_uri: "https://user.gini.net"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: >
            ./gradlew
            health-api-library:library:injectTestProperties
            health-api-library:library:connectedCheck
            -PtestClientId="$client_id" -PtestClientSecret="$client_secret"
            -PtestApiUri="$api_uri" -PtestUserCenterUri="$user_center_uri"

      - name: archive instrumented test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-instrumented-test-results
          path: health-api-library/library/build/outputs/androidTest-results/connected

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run checkstyle
        run: ./gradlew health-api-library:library:checkstyle

      - name: archive checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-checkstyle-report
          path: health-api-library/library/build/reports/checkstyle/*.html

  pmd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run pmd
        run: ./gradlew health-api-library:library:pmd

      - name: archive pmd report
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-pmd-report
          path: health-api-library/library/build/reports/pmd/*.html

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run android lint
        run: ./gradlew health-api-library:library:lint

      - name: archive android lint report
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-android-lint-report
          path: health-api-library/library/build/reports/lint-results*.html

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run detekt
        run: ./gradlew health-api-library:library:detekt

      - name: archive detekt report
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-detekt-report
          path: health-api-library/library/build/reports/detekt/*.html

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: run ktlint
        run: ./gradlew health-api-library:library:ktlintCheck

      - name: archive ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-ktlint-report
          path: health-api-library/library/build/reports/ktlint/**/*.html
          