name: Publish Health SDK Example App QA Build to Firebase App Distribution

permissions:
  content: read

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'health-sdk/**'
      - 'health-api-library/**'
      - 'core-api-library/**'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-publish
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}

jobs:
  check:
    uses: ./.github/workflows/health-sdk.check.yml
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}
      HEALTH_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD: ${{ secrets.HEALTH_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}
        
  publish_to_firebase_distribution:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: build release example app for QA
        run: >
          ./gradlew health-sdk:example-app:assembleQaRelease
          -PclientId="gini-mobile-test" 
          -PclientSecret="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"
          -PreleaseKeystoreFile="health_sdk_example.jks"
          -PreleaseKeystorePassword='${{ secrets.HEALTH_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'
          -PreleaseKeyAlias="health_sdk_example"
          -PreleaseKeyPassword='${{ secrets.HEALTH_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}'      

      - name: Check file existence
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "./health-sdk/example-app/build/outputs/apk/qa/release/example-app-qa-release.apk"
          fail: true

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g firebase-tools@13.17.0
        shell: bash

      - name: Distribute Health-sdk example apk to Firebase App Distribution
        id: distribute
        run: |
          chmod +x .github/publish_to_firebase.sh
          .github/publish_to_firebase.sh
        shell: bash
        env:
          INPUT_APPID: ${{secrets.GINI_HEALTH_SDK_EXAMPLE_APP_FIREBASE_ID}}
          INPUT_SERVICECREDENTIALSFILECONTENT: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          INPUT_FILE: health-sdk/example-app/build/outputs/apk/qa/release/example-app-qa-release.apk
          INPUT_GROUPS: testers
          INPUT_RELEASENOTES: |
            ${{ format('{{ {0} {1} }}', github.ref, github.sha) }}
            ${{ github.event.head_commit.message }}

      - name: Extract Jira ticket
        id: extract_jira_ticket
        run: |
          echo "Checking the last 3 commits for JIRA tickets..."
          jira_ticket_pattern='[A-Z]+-[0-9]+'
          jira_ticket=""

          commit_message=$(git log -1 --pretty=%B)
          jira_ticket=$(echo "$commit_message" | grep -oE "$jira_ticket_pattern" | head -1)

          if [[ -n "$jira_ticket" ]]; then
            echo "JIRA Ticket Found in Last Commit: $jira_ticket"
          else
            commit_message=$(git log --no-merges -1 --pretty=%B)
            jira_ticket=$(echo "$commit_message" | grep -oE "$jira_ticket_pattern" | head -1)

            if [[ -n "$jira_ticket" ]]; then
              echo "JIRA Ticket Found in Second Last Commit: $jira_ticket"
            else    
              commit_message=$(git log --no-merges -2 --pretty=%B)
              jira_ticket=$(echo "$commit_message" | grep -oE "$jira_ticket_pattern" | head -1)

              if [[ -n "$jira_ticket" ]]; then
                echo "JIRA Ticket Found in Third Last Commit: $jira_ticket"
              fi
            fi
          fi

          if [[ -n "$jira_ticket" ]]; then
            echo "JIRA_TICKET_NAME=${jira_ticket}" >> $GITHUB_ENV
          else
            echo "No JIRA Ticket found in the last 3 commits. Build link will not be posted to Jira."
            exit 1
          fi

      - name: Login to jira
        if: ${{ env.JIRA_TICKET_NAME != null }}
        uses: justin-jhg/gajira-login@3242a47d56cb5dd4373ed75b829d99ecdf5140df # v1.5
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_KEY }}

      - name: Comment on issue
        if: ${{ env.JIRA_TICKET_NAME != null }}
        uses: atlassian/gajira-comment@76589d6b6d0b94b1ca6b01171c01a6affb5d6701 # v3.0.1
        with:
          issue: ${{ env.JIRA_TICKET_NAME }}
          comment: Build health example app ${{ steps.distribute.outputs.FIREBASE_CONSOLE_URI }} and app tester build can be downloaded from here ${{ steps.distribute.outputs.TESTING_URI }}