name: Release docs for Health API Library

on:
  push:
    tags:
      - 'health-api-library;[0-9]+.[0-9]+.[0-9]+;doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get branch name
        id: branch
        shell: bash
        run: |
          # Get the branch ref that contains the tag in github.ref
          # (github.ref contains the tag because this workflow is triggered by tags: 
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
          branch_ref=$(git branch -r --contains "${{ github.ref }}")
          # Remove "origin/" prefix from branch_ref and trim whitespace
          branch_name=$(echo ${branch_ref/origin\/} | tr -d '[:space:]')
          echo "::set-output name=branch_name::$branch_name"
          echo "branch_name: $branch_name"

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.x'

      - name: release documentation
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'release_documentation'
          options: >
            { 
              "project_id": "health-api-library", 
              "module_id": "library",
              "documentation_title": "Gini Health API Library for Android",
              "is_stable_release": "${{ steps.branch.outputs.branch_name == 'main' }}",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-documentation
          path: health-api-library/library/build/docs
