name: Release docs for Health SDK

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - 'health-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
      - 'health-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9];doc**'
  workflow_call:
    secrets:
      MOBILE_CI_APP_ID:
        required: true
      MOBILE_CI_APP_PRIVATE_KEY:
        required: true

jobs:
  publish:
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.publish.docs.yml
    with:
      project_id: 'health-sdk'
      module_id: 'sdk'
      documentation_title: 'Gini Health SDK for Android'
      git_tag: ${{ github.ref }}
      artifact_name: 'health-sdk-documentation'
      artifact_path: 'health-sdk/sdk/build/docs'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
