name: Release Health API Library

on:
  push:
    tags:
      - 'health-api-library;[0-9]+.[0-9]+.[0-9]+'

jobs:
#  check:
#    uses: gini/gini-mobile-android/.github/workflows/health-api-library.check.yml@13559ed7f829b9373c5fbcf58c76d33feeb9d7f6

  release:
#    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'publish_to_maven'
          options: >
            { 
              "project_id": "health-api-library", 
              "module_id": "library", 
              "build_number": "${{ github.run_number }}",
              "git_tag": "${{ github.ref }}" 
            }
