name: Test the Health API Library
on: [push]
#  push:
#    paths:
#      - 'health-api-library/**'
jobs:
  test-health-api-library:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [22]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: avd cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: run instrumented tests
        env:
          client_id: ${{ secrets.HEALTH_API_LIBRARY_TEST_CLIENT_ID }}
          client_secret: ${{ secrets.HEALTH_API_LIBRARY_TEST_CLIENT_SECRET }}
          api_uri: "https://pay-api.gini.net"
          user_center_uri: "https://user.gini.net"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: >
            ./gradlew
            health-api-library:library:injectTestProperties
            health-api-library:library:connectedCheck
            -PtestClientId="$client_id" -PtestClientSecret="$client_secret"
            -PtestApiUri="$api_uri" -PtestUserCenterUri="$user_center_uri"

      - name: archive instrumented test results
        uses: actions/upload-artifact@v2
        with:
          name: health-api-library-instrumented-test-results
          path: health-api-library/library/build/outputs/androidTest-results/connected
