name: Release Health API Library

on:
  push:
    tags:
      - 'health-api-library;[0-9]+.[0-9]+.[0-9]+'

jobs:
  check:
    uses: gini/gini-mobile-android/.github/workflows/health-api-library.check.yml@main

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: "publish to gini's maven repo at https://repo.gini.net/nexus/content/repositories/open"
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'publish_to_maven_repo'
          options: >
            { 
              "repo_url": "https://repo.gini.net/nexus/content/repositories/open",
              "repo_user": "jenkins",
              "repo_password": "${{ secrets.GINI_EXTERNAL_NEXUS_PASSWORD }}",
              "project_id": "health-api-library", 
              "module_id": "library", 
              "build_number": "${{ github.run_number }}",
              "git_tag": "${{ github.ref }}",
              "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
              "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
            }
    
      - name: "publish to Maven Central staging repo at https://oss.sonatype.org/service/local/staging/deploy/maven2/"
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'publish_to_maven_snapshots_repo'
          options: >
            {
              "repo_url": "https://oss.sonatype.org/service/local/staging/deploy/maven2/",
              "repo_user": "alpar.gini",
              "repo_password": "${{ secrets.MAVEN_CENTRAL_PASSWORD }}",
              "project_id": "health-api-library",
              "module_id": "library",
              "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
              "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
            }

  release-documentation:
    needs: release
    uses: gini/gini-mobile-android/.github/workflows/health-api-library.docs.release.yml@main
      with:
        RELEASE_GITHUB_USER: ${{ secrets.RELEASE_GITHUB_USER }}
        RELEASE_GITHUB_PASSWORD: ${{ secrets.RELEASE_GITHUB_PASSWORD }}
