name: Release Internal Payment SDK

on:
  push:
    tags:
      - 'internal-payment-sdk;[0-9]+.[0-9]+.[0-9]+'
      - 'internal-payment-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9]'

jobs:
  check:
    uses: ./.github/workflows/internal-payment-sdk.check.yml

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true
    
      - name: "publish to Maven Central staging repo at https://oss.sonatype.org/service/local/staging/deploy/maven2/"
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'publish_to_maven_repo'
          options: >
            {
              "repo_url": "https://oss.sonatype.org/service/local/staging/deploy/maven2/",
              "repo_user": "${{ secrets.MAVEN_CENTRAL_USER_TOKEN_USERNAME }}",
              "repo_password": "${{ secrets.MAVEN_CENTRAL_USER_TOKEN_PASSWORD }}",
              "project_id": "internal-payment-sdk",
              "module_id": "sdk",
              "build_number": "${{ github.run_number }}",
              "git_tag": "${{ github.ref }}",
              "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
              "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
            }
