name: Release docs for Merchant SDK

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - 'merchant-sdk;[0-9]+.[0-9]+.[0-9]+;doc**'
      - 'merchant-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9];doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get branch name
        id: branch
        shell: bash
        run: |
          # Get the branch ref that contains the tag in github.ref
          # (github.ref contains the tag because this workflow is triggered by tags: 
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
          branch_ref=$(git branch -r --contains "${{ github.ref }}")
          # Remove "origin/" prefix from branch_ref and trim whitespace
          branch_name=$(echo ${branch_ref/origin\/} | tr -d '[:space:]')
          echo "::set-output name=branch_name::$branch_name"
          echo "branch_name: $branch_name"

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy2.7'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: release documentation
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7  # v3.1.0
        with:
          lane: 'release_documentation'
          options: >
            { 
              "project_id": "merchant-sdk", 
              "module_id": "sdk",
              "documentation_title": "Gini Merchant SDK for Android",
              "is_stable_release": "${{ steps.branch.outputs.branch_name == 'main' }}",
              "git_tag": "${{ github.ref }}",
              "ci": "true",
              "git_user": "${{ secrets.RELEASE_GITHUB_USER }}",
              "git_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}"
            }

      - name: archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: merchant-sdk-documentation
          path: merchant-sdk/sdk/build/docs
