name: Release Merchant SDK

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'merchant-sdk;[0-9]+.[0-9]+.[0-9]+'
      - 'merchant-sdk;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9]'

jobs:
  check:
    uses: ./.github/workflows/merchant-sdk.check.yml
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}
      MERCHANT_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD: ${{ secrets.MERCHANT_SDK_EXAMPLE_APP_KEYSTORE_PASSWORD }}
        
  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: setup ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: "publish to Maven Central staging repo at https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7  # v3.1.0
        with:
          lane: 'publish_to_maven_repo'
          options: >
            {
              "repo_url": "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/",
              "repo_user": "${{ secrets.MAVEN_CENTRAL_USER_TOKEN_USERNAME }}",
              "repo_password": "${{ secrets.MAVEN_CENTRAL_USER_TOKEN_PASSWORD }}",
              "project_id": "merchant-sdk",
              "module_id": "sdk",
              "build_number": "${{ github.run_number }}",
              "git_tag": "${{ github.ref }}",
              "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
              "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
            }

      - name: Upload staging repository to Central Portal
        env:
          PORTAL_NAMESPACE: net.gini
          TOKEN_USER: ${{ secrets.MAVEN_CENTRAL_USER_TOKEN_USERNAME }}
          TOKEN_PASS: ${{ secrets.MAVEN_CENTRAL_USER_TOKEN_PASSWORD }}
        run: |
          # Prepare the Bearer token for authentication (username:password base64)
          AUTH=$(printf "%s:%s" "$TOKEN_USER" "$TOKEN_PASS" | base64)
          # Trigger the upload of the staging repo to the Central Portal
          curl -X POST -H "Authorization: Bearer $AUTH" \
               "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/$PORTAL_NAMESPACE"

  release-documentation:
    needs: release
    uses: ./.github/workflows/merchant-sdk.docs.release.yml
    secrets:
      RELEASE_GITHUB_USER: ${{ secrets.RELEASE_GITHUB_USER }}
      RELEASE_GITHUB_PASSWORD: ${{ secrets.RELEASE_GITHUB_PASSWORD }}
